### ISSUE TITLE
displaying start rating on job archive page in listable theme

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [FacetWP/facetwp-star-rating#2]
I have defined a function display_listable_child_average_listing_rating modifying your average_listing_rating and overridden content-job_listing.php file of wp job manager plugin in child theme displaying the star rating  . and in my single job listing the star rating is displaying using your function, the problem is when I am going to next ppage using ajax pagination I can not get the star rating only when after reloading the page I am able to get the star rating , can you give some idea, how I can make it working.

**Comment by mgibbs189** [comment]
Please submit a support ticket for usage and customization questions. GitHub is for bugs and enhancements. Thanks.

**Comment by PrafullaKumarSahu** [comment]
already solved it .with
```
 $(document).on('facetwp-loaded', function(){ 
            --------------
            if ( FWP.loaded ){
                  ---------}
 ----- });    
```
